CREATE TABLE developers (id INT, name VARCHAR(100), specialization VARCHAR(100), experience VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE skills (id INT, name VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE projects (id INT, name VARCHAR(100), version VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE companies (id INT, name VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE customers (id INT, name VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE developers_skills (developer_id INT, skill_id INT, FOREIGN KEY (developer_id) REFERENCES developers(id), FOREIGN KEY (skill_id) REFERENCES skills(id));
CREATE TABLE projects_developers (project_id INT, developer_id INT, FOREIGN KEY (project_id) REFERENCES projects(id), FOREIGN KEY (developer_id) REFERENCES developers(id));
CREATE TABLE companies_projects (company_id INT, project_id INT, FOREIGN KEY (company_id) REFERENCES companies(id), FOREIGN KEY (project_id) REFERENCES projects(id));
CREATE TABLE customers_projects (customer_id INT, project_id INT, FOREIGN KEY (customer_id) REFERENCES customers(id), FOREIGN KEY (project_id) REFERENCES projects(id));
CREATE TABLE companies_projects_customers (company_id INT, project_id INT, customer_id INT, FOREIGN KEY (company_id) REFERENCES companies(id), FOREIGN KEY (project_id) REFERENCES projects(id), FOREIGN KEY (customer_id) REFERENCES customers(id));